insert into OPENING(ID,OPENING_NAME,MOVE1,MOVE2,TYPE,GAMBIT,LINK_MORE_INFO)values('1','Quen''s Gambit','d4 d5','c4','White',true,'https://en.wikipedia.org/wiki/Queen%27s_Gambit')
insert into OPENING(ID,OPENING_NAME,MOVE1,MOVE2,TYPE,GAMBIT,LINK_MORE_INFO)values('2','Bishop''s opening','e4 e5','Dc4','White',false,'https://en.wikipedia.org/wiki/Bishop%27s_Opening')
insert into OPENING(ID,OPENING_NAME,MOVE1,MOVE2,TYPE,GAMBIT,LINK_MORE_INFO)values('3','Vienna Game','e4 e5','Nc3','White',false,'https://en.wikipedia.org/wiki/Vienna_Game')
insert into OPENING(ID,OPENING_NAME,MOVE1,MOVE2,TYPE,GAMBIT,LINK_MORE_INFO)values('4','Philidor Defense','e4 e5','Nf3 d6','Black',false,'https://en.wikipedia.org/wiki/Philidor_Defence')
insert into OPENING(ID,OPENING_NAME,MOVE1,MOVE2,TYPE,GAMBIT,LINK_MORE_INFO)values('5','Sicilian Defence','e5 d5','c4','Black',false,'https://en.wikipedia.org/wiki/Sicilian_Defence')
insert into OPENING(ID,OPENING_NAME,MOVE1,MOVE2,TYPE,GAMBIT,LINK_MORE_INFO)values('6','King''s indian defence','d4 Nf6','c4 g6','White',false,'https://en.wikipedia.org/wiki/King%27s_Indian_Defence')
insert into VARIANT(ID,NAME,ID_PARENT_MOVE,MOVE)values(1,'Queen''s gambit Declined',1,'e6')
